version: "3.9"

services:
  app:
    image: node:14.16.0-alpine3.13
    ports:
      - "6080:3000"
    volumes:
      - ./:/src
      - "/src/node_modules"
    working_dir: /src
    command: /bin/sh -c "npm install && npm run prisma migrate deploy && npm run start:dev"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: 
      - .env
