version: "3.9"

services:
  app:
    image: node:14.16.0-alpine3.13
    ports:
      - "6080:80"
    volumes:
      - ./:/src
    working_dir: /src
    command: npm run start:dev

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file: 
      - .env
